name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       node-version:
  #         - current
  #         - lts/*
  #         - lts/-1

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: pnpm
  #     - run: pnpm install
  #     - run: pnpm run build --if-present
  #     - run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js latest LTS version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint
